spring.application.name=barbearia

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

joinfaces.primefaces.theme=luna-amber


#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=meubanco;encrypt=true;trustServerCertificate=true
#
#spring.datasource.username=sa
#spring.datasource.password=senha
#
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true